Improve scripts by ensuring enabling more strict execution

diff --git a/xcrestore b/xcrestore
--- a/xcrestore
+++ b/xcrestore
@@ -4,6 +4,9 @@
 # Author:   John T McIntosh (http://johntmcintosh.com)
 ###
 
+set -o errexit # Exit if any statement returns a non-true return value (non-zero).
+set -o nounset # Exit on use of an uninitialized variable
+
 # Get the source directory to use for relative paths when referencing other scripts
 CALLING_DIR="${BASH_SOURCE%/*}"
 BINARY=`readlink "$CALLING_DIR/xcunsign"`
@@ -17,8 +20,7 @@ fi
 source "$ROOT_DIR/lib/input.sh"
 
 # If the app is already signed, there's nothing that needs to be done
-$ROOT_DIR/lib/verify_codesign.rb "$BINARY_PATH"
-if [ $? -eq 0 ]; then
+if $ROOT_DIR/lib/verify_codesign.rb "$BINARY_PATH"; then 
     echo "${GREEN}$BINARY_PATH is already signed.${NC}"
     exit 0
 fi
@@ -26,19 +28,20 @@ fi
 # Ensure that the app has a signed copy that can be restored
 # If the return code of the verify_codesign call is 0, then
 # we have a legitimately signed binary.
-$ROOT_DIR/lib/verify_codesign.rb "$SIGNED_PATH"
-if [ ! $? -eq 0 ]; then
+if ! $ROOT_DIR/lib/verify_codesign.rb "$SIGNED_PATH"; then
     echo "${RED}There no file at ${SIGNED_PATH} to restore.${NC}"
-    exit 1
+    exit 1 
 fi
 
 # Delete the existing binary, and replace it with the signed copy
 echo "Setting $BINARY_PATH to signed copy"
 rm "$BINARY_PATH"
 cp -p "$SIGNED_PATH" "$BINARY_PATH"
-echo "${GREEN}Xcode $INPUT_VERSION has been re-signed.${NC}"
+echo "Signed binary restored."
 
 # Restore Xcode's app icon to the standard icon
 $ROOT_DIR/bin/fileicon rm $XCODE_PATH
 killall Finder
 killall Dock
+
+echo "${GREEN}Xcode $INPUT_VERSION signature has been restored.${NC}"
diff --git a/xcunsign b/xcunsign
--- a/xcunsign
+++ b/xcunsign
@@ -4,6 +4,9 @@
 # Author:   John T McIntosh (http://johntmcintosh.com)
 ###
 
+set -o errexit # Exit if any statement returns a non-true return value (non-zero).
+set -o nounset # Exit on use of an uninitialized variable
+
 # Get the source directory to use for relative paths when referencing other scripts
 CALLING_DIR="${BASH_SOURCE%/*}"
 BINARY=`readlink "$CALLING_DIR/xcunsign"`
@@ -17,8 +20,7 @@ fi
 source "$ROOT_DIR/lib/input.sh"
 
 # If the app is already unsigned, there's nothing that needs to be done
-$ROOT_DIR/lib/verify_codesign.rb "$BINARY_PATH"
-if [ ! $? -eq 0 ]; then
+if ! $ROOT_DIR/lib/verify_codesign.rb "$BINARY_PATH"; then
     echo "${GREEN}$BINARY_PATH is already unsigned.${NC}"
     exit 0
 fi
@@ -31,15 +33,16 @@ echo "Copying standard binary to $SIGNED_PATH"
 ditto $BINARY_PATH $SIGNED_PATH
 
 echo "Executing unsign now..."
-echo `unsign $BINARY_PATH $UNSIGNED_PATH`
+$ROOT_DIR/bin/unsign $BINARY_PATH $UNSIGNED_PATH
 
 # Delete the existing binary, and replace it with the unsigned copy
 echo "Setting $BINARY_PATH to unsigned copy"
 rm "$BINARY_PATH"
 cp -p "$UNSIGNED_PATH" "$BINARY_PATH"
-echo "${GREEN}Xcode $INPUT_VERSION has been unsigned.${NC}"
 
 # Set Xcode's app icon to the unsigned icon
 $ROOT_DIR/bin/fileicon set $XCODE_PATH $ROOT_DIR/resources/XcodeUnsigned.png
 killall Finder
 killall Dock
+
+echo "${GREEN}Xcode $INPUT_VERSION has been unsigned.${NC}"
